project:
  type: website

website:
  title: "Cosme Aquino Ovelar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: simulations.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

