project:
  type: website

website:
  title: "Cosme Aquino Ovelar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: simulations.qmd
      - href: volunteering.qmd
      - href: spotlight.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto


